name       : autoconf-archive
version    : 2015.09.25
release    : 1
source     :
    - http://ftp.heanet.ie/mirrors/gnu/autoconf-archive/autoconf-archive-2015.09.25.tar.xz : 7c0467a5dbd2340153bca5a477bd92fbc951d9ee3cbed92f16f6bf08ac0c350a
license    : GPL-3.0-with-autoconf-exception
summary    : A collection of macros for Autoconf
description: |
    The GNU Autoconf Archive is a collection of more than 500 macros for [GNU Autoconf](http://www.gnu.org/software/autoconf) that have been contributed as free software by friendly supporters of the cause from all over the Internet. Every single one of those macros can be re-used without imposing any restrictions whatsoever on the licensing of the generated configure script. In particular, it is possible to use all those macros in configure scripts that are meant for non-free software. This policy is unusual for a Free Software Foundation project. The FSF firmly believes that software ought to be free, and software licenses like the GPL are specifically designed to ensure that derivative work based on free software must be free as well.
    In case of Autoconf, however, an exception has been made, because Autoconf is at such a pivotal position in the software development tool chain that the benefits from having this tool available as widely as possible outweigh the disadvantage that some authors may choose to use it, too, for proprietary software.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
